[tool.pyright]
exclude = [
    "**/.venv",
    "**/node_modules",
    "**/__pycache__",
    "**/aw_best"
]

[tool.ruff]
exclude = [
    "**/aw_best"
]



[project]
name = "surmodelsopt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TreeCapitator", email = "igor.misterowicz@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "hydra-core==1.3.6",
    "numpy==2.5.2",
    "omegaconf==2.3.1",
    "pandas==3.0.5",
    "pytorch-lightning==2.6.5",
    "pyyaml==6.0.3",
    "ruff>=0.16.6",
    "scikit-learn==1.9.0",
    "torch==2.14.0",
]

[project.scripts]
surmodelsopt = "surmodelsopt:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
