[project]
name = "surmodelsopt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TreeCapitator", email = "igor.misterowicz@gmail.com" }
]
requires-python = ">=3.9, <3.10"
dependencies = [
    "pandas==1.1.5",
    "numpy==1.19.5",
    "pytorch-lightning==1.5.10",
    "click==8.0.4",
    "scikit-learn==1.0.1",
    "lightgbm==3.3.2",
    "hyperopt==0.2.7",
    "matplotlib==3.5.1",
    "torch==1.10.2",
    "torchvision==0.11.3",
    "tensorboard==2.8.0",
    "protobuf<=3.20.3",
    "black",
    "hydra-core",
    "pyright>=1.1.411",
    "ruff>=0.16.6",
]

[project.scripts]
surmodelsopt = "surmodelsopt:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cu113"
url = "https://download.pytorch.org/whl/cu113"

[tool.uv]
index-strategy = "unsafe-best-match"
